version: '3.8'
services:
  mongodb:
    image: mongo
    volumes:
      - alert_db_test:/data/db
    ports:
      - "27017:27017"

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  ms:
    build: ./ms
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: "mongodb+srv://fouzan:EGPmSVfHfoa1LUW7@trial-alert-system.fezsxkj.mongodb.net/?retryWrites=true&w=majority&appName=trial-alert-system"
      PORT: 5000
      SECRET_KEY: "/nHQRiJoZM/I0kfArHzxSs7RNrVzQRVlCNrbkyprw6A="
      EMAIL_PASS: "ttjn qlfu jlbh fiwe"
      EMAIL_USER: "q476088@gmail.com"
      ENCRYPTION_KEY: "X4yIwyPnckxQFOPDbSGUQSPxHLn5RHUGnVzZThk4vIw="
      SIGNING_KEY: "jQbCb/GcrXaU9sUrZHXZFCwwkPEoaMUZMIYfSJ2Jb0CZmwRLJ2z4xB8iFuygoJ4hvsfNfMUrVOtBdqKSLhVNsg=="

  ats:
    build: ./ats
    depends_on:
      - kafka
      - mongodb
    environment:
      KAFKA_BROKER: "kafka:9092"
      MONGODB_URI: "mongodb+srv://fouzan:EGPmSVfHfoa1LUW7@trial-alert-system.fezsxkj.mongodb.net/?retryWrites=true&w=majority&appName=trial-alert-system"

  dqs:
    build: ./dqs
    depends_on:
      - kafka
      - mongodb
    environment:
      KAFKA_BROKER: "kafka:9092"
      MONGODB_URI: "mongodb+srv://fouzan:EGPmSVfHfoa1LUW7@trial-alert-system.fezsxkj.mongodb.net/?retryWrites=true&w=majority&appName=trial-alert-system"
      ENCRYPTION_KEY: "X4yIwyPnckxQFOPDbSGUQSPxHLn5RHUGnVzZThk4vIw="
      SIGNING_KEY: "jQbCb/GcrXaU9sUrZHXZFCwwkPEoaMUZMIYfSJ2Jb0CZmwRLJ2z4xB8iFuygoJ4hvsfNfMUrVOtBdqKSLhVNsg=="

  aas:
    build: ./aas
    depends_on:
      - kafka
      - mongodb
    environment:
      KAFKA_BROKER: "kafka:9092"
      MONGODB_URI: "mongodb+srv://fouzan:EGPmSVfHfoa1LUW7@trial-alert-system.fezsxkj.mongodb.net/?retryWrites=true&w=majority&appName=trial-alert-system"

volumes:
  alert_db_test:

networks:
  default:
    driver: bridge
